const ALL_CBOM_COMPONENTS = [
  { id:'CBOM-001', asset:'api.pnbindia.in',          algorithm:'RSA-PKCS1-SHA256',   keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'ECDH-RSA',       status:'critical',    riskScore:91, certExpiry:'15 Mar 2025', expired:true,  type:'API',        issuer:'DigiCert Inc' },
  { id:'CBOM-002', asset:'netbanking.pnbindia.in',   algorithm:'ECDSA-SHA384',        keySize:'256-bit',   tlsVer:'1.2', keyExchange:'ECDHE-RSA',      status:'high',        riskScore:74, certExpiry:'01 Jun 2026', expired:false, type:'Web Server', issuer:'Sectigo CA' },
  { id:'CBOM-003', asset:'vpn.pnbindia.in',          algorithm:'RSA-PKCS1-SHA1',      keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'RSA',            status:'critical',    riskScore:95, certExpiry:'01 Jan 2026', expired:false, type:'VPN',        issuer:'Entrust CA' },
  { id:'CBOM-004', asset:'mobile.pnbindia.in',       algorithm:'ECDH-SHA256',         keySize:'256-bit',   tlsVer:'1.3', keyExchange:'ECDHE',          status:'medium',      riskScore:52, certExpiry:'15 Aug 2026', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-005', asset:'corp.pnbindia.in',         algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:18, certExpiry:'01 Feb 2027', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-006', asset:'payments.pnbindia.in',     algorithm:'RSA-2048',            keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'ECDH-RSA',       status:'critical',    riskScore:88, certExpiry:'30 Sep 2025', expired:false, type:'API',        issuer:'GlobalSign' },
  { id:'CBOM-007', asset:'sso.pnbindia.in',          algorithm:'ECDSA-P256',          keySize:'256-bit',   tlsVer:'1.2', keyExchange:'ECDHE-RSA',      status:'high',        riskScore:71, certExpiry:'10 Dec 2025', expired:false, type:'API',        issuer:'Sectigo CA' },
  { id:'CBOM-008', asset:'cdn.pnbindia.in',          algorithm:'ML-DSA-65',           keySize:'3309-bit',  tlsVer:'1.3', keyExchange:'ML-KEM-768',     status:'quantum-safe',riskScore:5,  certExpiry:'01 Mar 2027', expired:false, type:'Web Server', issuer:'PNB PQC CA' },
  { id:'CBOM-009', asset:'trade.pnbindia.in',        algorithm:'DHE-RSA-2048',        keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'DHE-RSA',        status:'high',        riskScore:78, certExpiry:'20 Jul 2025', expired:false, type:'Web Server', issuer:'DigiCert Inc' },
  { id:'CBOM-010', asset:'forex.pnbindia.in',        algorithm:'AES-128-CBC',         keySize:'128-bit',   tlsVer:'1.2', keyExchange:'ECDHE-RSA',      status:'medium',      riskScore:49, certExpiry:'05 Nov 2025', expired:false, type:'Web Server', issuer:'Sectigo CA' },
  { id:'CBOM-011', asset:'legacy.pnbindia.in',       algorithm:'RSA-PKCS1-SHA1',      keySize:'1024-bit',  tlsVer:'1.1', keyExchange:'RSA',            status:'critical',    riskScore:98, certExpiry:'01 Dec 2024', expired:true,  type:'Web Server', issuer:'Comodo CA' },
  { id:'CBOM-012', asset:'b2b-api.pnbindia.in',      algorithm:'RSA-PKCS1-SHA256',    keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'DHE-RSA',        status:'critical',    riskScore:87, certExpiry:'14 Aug 2025', expired:false, type:'API',        issuer:'GlobalSign' },
  { id:'CBOM-013', asset:'admin.pnbindia.in',        algorithm:'RSA-PKCS1-SHA256',    keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'ECDHE-RSA',      status:'high',        riskScore:73, certExpiry:'30 Oct 2025', expired:false, type:'Web Server', issuer:'DigiCert Inc' },
  { id:'CBOM-014', asset:'ib.pnbindia.in',           algorithm:'RSA-PKCS1-SHA256',    keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'ECDHE-RSA',      status:'high',        riskScore:72, certExpiry:'22 Sep 2025', expired:false, type:'Web Server', issuer:'Sectigo CA' },
  { id:'CBOM-015', asset:'mobilebank.pnbindia.in',   algorithm:'ECDSA-P256',          keySize:'256-bit',   tlsVer:'1.2', keyExchange:'ECDHE-RSA',      status:'high',        riskScore:69, certExpiry:'18 Jan 2026', expired:false, type:'API',        issuer:"Let's Encrypt" },
  { id:'CBOM-016', asset:'docs.pnbindia.in',         algorithm:'ECDSA-P256',          keySize:'256-bit',   tlsVer:'1.3', keyExchange:'X25519',         status:'medium',      riskScore:48, certExpiry:'01 Apr 2026', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-017', asset:'internal.pnbindia.in',     algorithm:'ECDSA-P384',          keySize:'384-bit',   tlsVer:'1.3', keyExchange:'ECDHE',          status:'medium',      riskScore:44, certExpiry:'15 May 2026', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-018', asset:'portal.pnbindia.in',       algorithm:'ECDSA-P256',          keySize:'256-bit',   tlsVer:'1.3', keyExchange:'X25519',         status:'medium',      riskScore:46, certExpiry:'01 Jul 2026', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-019', asset:'loans.pnbindia.in',        algorithm:'ECDSA-P256',          keySize:'256-bit',   tlsVer:'1.3', keyExchange:'ECDHE',          status:'medium',      riskScore:51, certExpiry:'20 Aug 2026', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-020', asset:'cards.pnbindia.in',        algorithm:'ECDSA-P384',          keySize:'384-bit',   tlsVer:'1.3', keyExchange:'X25519',         status:'medium',      riskScore:43, certExpiry:'10 Sep 2026', expired:false, type:'API',        issuer:'Sectigo CA' },
  { id:'CBOM-021', asset:'static.pnbindia.in',       algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:15, certExpiry:'01 Feb 2027', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-022', asset:'reporting.pnbindia.in',    algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:14, certExpiry:'01 Mar 2027', expired:false, type:'API',        issuer:"Let's Encrypt" },
  { id:'CBOM-023', asset:'analytics.pnbindia.in',    algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:16, certExpiry:'15 Mar 2027', expired:false, type:'API',        issuer:"Let's Encrypt" },
  { id:'CBOM-024', asset:'gateway.pnbindia.in',      algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:13, certExpiry:'01 Apr 2027', expired:false, type:'API',        issuer:"Let's Encrypt" },
  { id:'CBOM-025', asset:'assets.pnbindia.in',       algorithm:'ML-DSA-65',           keySize:'3309-bit',  tlsVer:'1.3', keyExchange:'ML-KEM-768',     status:'quantum-safe',riskScore:4,  certExpiry:'15 Mar 2027', expired:false, type:'Web Server', issuer:'PNB PQC CA' },
  { id:'CBOM-026', asset:'media.pnbindia.in',        algorithm:'SLH-DSA',             keySize:'7856-bit',  tlsVer:'1.3', keyExchange:'ML-KEM-1024',    status:'quantum-safe',riskScore:3,  certExpiry:'01 Apr 2027', expired:false, type:'Web Server', issuer:'PNB PQC CA' },
  { id:'CBOM-027', asset:'secure-api.pnbindia.in',   algorithm:'ML-DSA-65',           keySize:'3309-bit',  tlsVer:'1.3', keyExchange:'ML-KEM-768',     status:'quantum-safe',riskScore:5,  certExpiry:'15 Apr 2027', expired:false, type:'API',        issuer:'PNB PQC CA' },
  { id:'CBOM-028', asset:'pqc-test.pnbindia.in',     algorithm:'ML-DSA-87',           keySize:'4627-bit',  tlsVer:'1.3', keyExchange:'ML-KEM-1024',    status:'quantum-safe',riskScore:2,  certExpiry:'01 May 2027', expired:false, type:'API',        issuer:'PNB PQC CA' },
  { id:'CBOM-029', asset:'infra.pnbindia.in',        algorithm:'ML-DSA-65',           keySize:'3309-bit',  tlsVer:'1.3', keyExchange:'ML-KEM-768',     status:'quantum-safe',riskScore:4,  certExpiry:'01 May 2027', expired:false, type:'Web Server', issuer:'PNB PQC CA' },
  { id:'CBOM-030', asset:'cloud.pnbindia.in',        algorithm:'SLH-DSA',             keySize:'7856-bit',  tlsVer:'1.3', keyExchange:'ML-KEM-1024',    status:'quantum-safe',riskScore:3,  certExpiry:'15 May 2027', expired:false, type:'Web Server', issuer:'PNB PQC CA' },
  // Critical/High mix — branch/region assets
  { id:'CBOM-031', asset:'branch1.pnbindia.in',      algorithm:'RSA-PKCS1-SHA256',    keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'RSA',            status:'critical',    riskScore:90, certExpiry:'20 Mar 2025', expired:true,  type:'Web Server', issuer:'DigiCert Inc' },
  { id:'CBOM-032', asset:'branch2.pnbindia.in',      algorithm:'RSA-PKCS1-SHA1',      keySize:'1024-bit',  tlsVer:'1.1', keyExchange:'RSA',            status:'critical',    riskScore:96, certExpiry:'10 Feb 2025', expired:true,  type:'Web Server', issuer:'Comodo CA' },
  { id:'CBOM-033', asset:'branch3.pnbindia.in',      algorithm:'RSA-PKCS1-SHA256',    keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'DHE-RSA',        status:'critical',    riskScore:85, certExpiry:'01 Apr 2025', expired:false, type:'Web Server', issuer:'GlobalSign' },
  { id:'CBOM-034', asset:'region1.pnbindia.in',      algorithm:'RSA-2048',            keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'ECDH-RSA',       status:'critical',    riskScore:89, certExpiry:'15 Jun 2025', expired:false, type:'Web Server', issuer:'DigiCert Inc' },
  { id:'CBOM-035', asset:'region2.pnbindia.in',      algorithm:'DHE-RSA-2048',        keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'DHE-RSA',        status:'high',        riskScore:76, certExpiry:'01 Jul 2025', expired:false, type:'Web Server', issuer:'GlobalSign' },
  { id:'CBOM-036', asset:'region3.pnbindia.in',      algorithm:'ECDSA-SHA384',        keySize:'256-bit',   tlsVer:'1.2', keyExchange:'ECDHE-RSA',      status:'high',        riskScore:70, certExpiry:'22 Aug 2025', expired:false, type:'Web Server', issuer:'Sectigo CA' },
  { id:'CBOM-037', asset:'api-v2.pnbindia.in',       algorithm:'RSA-PKCS1-SHA256',    keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'ECDHE-RSA',      status:'high',        riskScore:75, certExpiry:'30 Sep 2025', expired:false, type:'API',        issuer:'DigiCert Inc' },
  { id:'CBOM-038', asset:'api-v3.pnbindia.in',       algorithm:'ECDSA-SHA384',        keySize:'256-bit',   tlsVer:'1.2', keyExchange:'ECDHE-RSA',      status:'high',        riskScore:68, certExpiry:'15 Oct 2025', expired:false, type:'API',        issuer:'Sectigo CA' },
  { id:'CBOM-039', asset:'svc1.pnbindia.in',         algorithm:'RSA-2048',            keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'RSA',            status:'critical',    riskScore:92, certExpiry:'05 May 2025', expired:false, type:'API',        issuer:'GlobalSign' },
  { id:'CBOM-040', asset:'svc2.pnbindia.in',         algorithm:'RSA-PKCS1-SHA256',    keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'DHE-RSA',        status:'critical',    riskScore:86, certExpiry:'18 Jun 2025', expired:false, type:'API',        issuer:'DigiCert Inc' },
  // Medium risk assets
  { id:'CBOM-041', asset:'app1.pnbindia.in',         algorithm:'ECDH-SHA256',         keySize:'256-bit',   tlsVer:'1.3', keyExchange:'ECDHE',          status:'medium',      riskScore:50, certExpiry:'01 Sep 2026', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-042', asset:'app2.pnbindia.in',         algorithm:'AES-128-CBC',         keySize:'128-bit',   tlsVer:'1.2', keyExchange:'ECDHE-RSA',      status:'medium',      riskScore:47, certExpiry:'15 Oct 2026', expired:false, type:'Web Server', issuer:'Sectigo CA' },
  { id:'CBOM-043', asset:'app3.pnbindia.in',         algorithm:'ECDSA-P256',          keySize:'256-bit',   tlsVer:'1.3', keyExchange:'X25519',         status:'medium',      riskScore:45, certExpiry:'01 Nov 2026', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-044', asset:'partner1.pnbindia.in',     algorithm:'ECDSA-P384',          keySize:'384-bit',   tlsVer:'1.3', keyExchange:'ECDHE',          status:'medium',      riskScore:42, certExpiry:'20 Dec 2026', expired:false, type:'API',        issuer:'Sectigo CA' },
  { id:'CBOM-045', asset:'partner2.pnbindia.in',     algorithm:'ECDH-SHA256',         keySize:'256-bit',   tlsVer:'1.3', keyExchange:'X25519',         status:'medium',      riskScore:53, certExpiry:'10 Jan 2027', expired:false, type:'API',        issuer:"Let's Encrypt" },
  { id:'CBOM-046', asset:'svc3.pnbindia.in',         algorithm:'AES-128-CBC',         keySize:'128-bit',   tlsVer:'1.2', keyExchange:'ECDHE-RSA',      status:'medium',      riskScore:48, certExpiry:'25 Feb 2026', expired:false, type:'API',        issuer:'Sectigo CA' },
  { id:'CBOM-047', asset:'branch4.pnbindia.in',      algorithm:'ECDSA-P256',          keySize:'256-bit',   tlsVer:'1.3', keyExchange:'ECDHE',          status:'medium',      riskScore:46, certExpiry:'01 Mar 2026', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-048', asset:'region4.pnbindia.in',      algorithm:'ECDSA-P384',          keySize:'384-bit',   tlsVer:'1.3', keyExchange:'X25519',         status:'medium',      riskScore:41, certExpiry:'15 Apr 2026', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-049', asset:'branch5.pnbindia.in',      algorithm:'ECDH-SHA256',         keySize:'256-bit',   tlsVer:'1.2', keyExchange:'ECDHE-RSA',      status:'medium',      riskScore:55, certExpiry:'14 Mar 2026', expired:false, type:'Web Server', issuer:'Sectigo CA' },
  { id:'CBOM-050', asset:'app4.pnbindia.in',         algorithm:'AES-128-CBC',         keySize:'128-bit',   tlsVer:'1.2', keyExchange:'ECDHE-RSA',      status:'medium',      riskScore:50, certExpiry:'20 Mar 2026', expired:false, type:'Web Server', issuer:'Sectigo CA' },
  // PQC-ready assets
  { id:'CBOM-051', asset:'api-v4.pnbindia.in',       algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:17, certExpiry:'01 May 2027', expired:false, type:'API',        issuer:"Let's Encrypt" },
  { id:'CBOM-052', asset:'svc4.pnbindia.in',         algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:16, certExpiry:'15 May 2027', expired:false, type:'API',        issuer:"Let's Encrypt" },
  { id:'CBOM-053', asset:'partner3.pnbindia.in',     algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:19, certExpiry:'01 Jun 2027', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-054', asset:'region5.pnbindia.in',      algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:15, certExpiry:'15 Jun 2027', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-055', asset:'branch6.pnbindia.in',      algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:14, certExpiry:'01 Jul 2027', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-056', asset:'app5.pnbindia.in',         algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:18, certExpiry:'15 Jul 2027', expired:false, type:'API',        issuer:"Let's Encrypt" },
  { id:'CBOM-057', asset:'partner4.pnbindia.in',     algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:12, certExpiry:'01 Aug 2027', expired:false, type:'API',        issuer:"Let's Encrypt" },
  { id:'CBOM-058', asset:'svc5.pnbindia.in',         algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:11, certExpiry:'15 Aug 2027', expired:false, type:'API',        issuer:"Let's Encrypt" },
  { id:'CBOM-059', asset:'region6.pnbindia.in',      algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:13, certExpiry:'01 Sep 2027', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-060', asset:'branch7.pnbindia.in',      algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:16, certExpiry:'15 Sep 2027', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-061', asset:'api-v5.pnbindia.in',       algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:15, certExpiry:'01 Oct 2027', expired:false, type:'API',        issuer:"Let's Encrypt" },
  { id:'CBOM-062', asset:'app6.pnbindia.in',         algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:17, certExpiry:'15 Oct 2027', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  // More quantum-safe
  { id:'CBOM-063', asset:'secure-gw.pnbindia.in',    algorithm:'ML-DSA-87',           keySize:'4627-bit',  tlsVer:'1.3', keyExchange:'ML-KEM-1024',    status:'quantum-safe',riskScore:2,  certExpiry:'01 Jun 2027', expired:false, type:'API',        issuer:'PNB PQC CA' },
  { id:'CBOM-064', asset:'pqc-prod.pnbindia.in',     algorithm:'ML-DSA-65',           keySize:'3309-bit',  tlsVer:'1.3', keyExchange:'ML-KEM-768',     status:'quantum-safe',riskScore:4,  certExpiry:'15 Jun 2027', expired:false, type:'Web Server', issuer:'PNB PQC CA' },
  { id:'CBOM-065', asset:'vault.pnbindia.in',        algorithm:'SLH-DSA',             keySize:'7856-bit',  tlsVer:'1.3', keyExchange:'ML-KEM-1024',    status:'quantum-safe',riskScore:1,  certExpiry:'01 Jul 2027', expired:false, type:'API',        issuer:'PNB PQC CA' },
  // More critical/high
  { id:'CBOM-066', asset:'branch8.pnbindia.in',      algorithm:'RSA-PKCS1-SHA1',      keySize:'1024-bit',  tlsVer:'1.0', keyExchange:'RSA',            status:'critical',    riskScore:99, certExpiry:'01 Nov 2024', expired:true,  type:'Web Server', issuer:'Comodo CA' },
  { id:'CBOM-067', asset:'branch9.pnbindia.in',      algorithm:'RSA-PKCS1-SHA256',    keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'RSA',            status:'critical',    riskScore:89, certExpiry:'12 Mar 2026', expired:false, type:'Web Server', issuer:'DigiCert Inc' },
  { id:'CBOM-068', asset:'region7.pnbindia.in',      algorithm:'RSA-2048',            keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'ECDH-RSA',       status:'critical',    riskScore:87, certExpiry:'25 Mar 2026', expired:false, type:'Web Server', issuer:'GlobalSign' },
  { id:'CBOM-069', asset:'svc6.pnbindia.in',         algorithm:'DHE-RSA-2048',        keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'DHE-RSA',        status:'high',        riskScore:77, certExpiry:'01 Apr 2026', expired:false, type:'API',        issuer:'DigiCert Inc' },
  { id:'CBOM-070', asset:'svc7.pnbindia.in',         algorithm:'ECDSA-SHA384',        keySize:'256-bit',   tlsVer:'1.2', keyExchange:'ECDHE-RSA',      status:'high',        riskScore:72, certExpiry:'15 Apr 2026', expired:false, type:'API',        issuer:'Sectigo CA' },
  { id:'CBOM-071', asset:'partner5.pnbindia.in',     algorithm:'RSA-PKCS1-SHA256',    keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'DHE-RSA',        status:'high',        riskScore:74, certExpiry:'01 May 2026', expired:false, type:'Web Server', issuer:'GlobalSign' },
  { id:'CBOM-072', asset:'app7.pnbindia.in',         algorithm:'ECDSA-SHA384',        keySize:'256-bit',   tlsVer:'1.2', keyExchange:'ECDHE-RSA',      status:'high',        riskScore:68, certExpiry:'15 May 2026', expired:false, type:'Web Server', issuer:'Sectigo CA' },
  // Medium
  { id:'CBOM-073', asset:'branch10.pnbindia.in',     algorithm:'ECDSA-P256',          keySize:'256-bit',   tlsVer:'1.3', keyExchange:'ECDHE',          status:'medium',      riskScore:44, certExpiry:'01 Jun 2026', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-074', asset:'region8.pnbindia.in',      algorithm:'ECDSA-P384',          keySize:'384-bit',   tlsVer:'1.3', keyExchange:'X25519',         status:'medium',      riskScore:40, certExpiry:'15 Jun 2026', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-075', asset:'app8.pnbindia.in',         algorithm:'AES-128-CBC',         keySize:'128-bit',   tlsVer:'1.2', keyExchange:'ECDHE-RSA',      status:'medium',      riskScore:51, certExpiry:'01 Jul 2026', expired:false, type:'Web Server', issuer:'Sectigo CA' },
  { id:'CBOM-076', asset:'svc8.pnbindia.in',         algorithm:'ECDH-SHA256',         keySize:'256-bit',   tlsVer:'1.3', keyExchange:'ECDHE',          status:'medium',      riskScore:54, certExpiry:'15 Jul 2026', expired:false, type:'API',        issuer:"Let's Encrypt" },
  // More PQC-ready
  { id:'CBOM-077', asset:'partner6.pnbindia.in',     algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:14, certExpiry:'01 Nov 2027', expired:false, type:'API',        issuer:"Let's Encrypt" },
  { id:'CBOM-078', asset:'branch11.pnbindia.in',     algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:16, certExpiry:'15 Nov 2027', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  { id:'CBOM-079', asset:'region9.pnbindia.in',      algorithm:'ML-KEM-768',          keySize:'1184-bit',  tlsVer:'1.3', keyExchange:'X25519Kyber768', status:'pqc-ready',   riskScore:15, certExpiry:'01 Dec 2027', expired:false, type:'Web Server', issuer:"Let's Encrypt" },
  // Critical tail
  { id:'CBOM-080', asset:'branch12.pnbindia.in',     algorithm:'RSA-PKCS1-SHA1',      keySize:'1024-bit',  tlsVer:'1.0', keyExchange:'RSA',            status:'critical',    riskScore:97, certExpiry:'15 Oct 2024', expired:true,  type:'Web Server', issuer:'Comodo CA' },
  { id:'CBOM-081', asset:'svc9.pnbindia.in',         algorithm:'RSA-2048',            keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'RSA',            status:'critical',    riskScore:90, certExpiry:'01 Sep 2025', expired:false, type:'API',        issuer:'GlobalSign' },
  { id:'CBOM-082', asset:'region10.pnbindia.in',     algorithm:'RSA-PKCS1-SHA256',    keySize:'2048-bit',  tlsVer:'1.2', keyExchange:'DHE-RSA',        status:'high',        riskScore:73, certExpiry:'10 Apr 2026', expired:false, type:'Web Server', issuer:'DigiCert Inc' },
  // Quantum safe tail
  { id:'CBOM-083', asset:'pqc-staging.pnbindia.in',  algorithm:'ML-DSA-65',           keySize:'3309-bit',  tlsVer:'1.3', keyExchange:'ML-KEM-768',     status:'quantum-safe',riskScore:5,  certExpiry:'01 Aug 2027', expired:false, type:'Web Server', issuer:'PNB PQC CA' },
  { id:'CBOM-084', asset:'secure-cdn.pnbindia.in',   algorithm:'SLH-DSA',             keySize:'7856-bit',  tlsVer:'1.3', keyExchange:'ML-KEM-1024',    status:'quantum-safe',riskScore:2,  certExpiry:'15 Aug 2027', expired:false, type:'Web Server', issuer:'PNB PQC CA' },
  { id:'CBOM-085', asset:'pqc-api.pnbindia.in',      algorithm:'ML-DSA-87',           keySize:'4627-bit',  tlsVer:'1.3', keyExchange:'ML-KEM-1024',    status:'quantum-safe',riskScore:1,  certExpiry:'01 Sep 2027', expired:false, type:'API',        issuer:'PNB PQC CA' },
];

const ALGO_DISTRIBUTION = [
  { algo:'RSA-PKCS1-SHA256', count:89,  safe:false, color:'#EF4444' },
  { algo:'ECDSA-SHA384',     count:67,  safe:false, color:'#F97316' },
  { algo:'ECDH-SHA256',      count:54,  safe:false, color:'#F97316' },
  { algo:'AES-128-CBC',      count:43,  safe:false, color:'#F59E0B' },
  { algo:'RSA-PKCS1-SHA1',   count:31,  safe:false, color:'#EF4444' },
  { algo:'DHE-RSA-2048',     count:28,  safe:false, color:'#F97316' },
  { algo:'ECDSA-P256',       count:22,  safe:false, color:'#F59E0B' },
  { algo:'AES-256-GCM',      count:18,  safe:true,  color:'#10B981' },
  { algo:'ML-KEM-768',       count:14,  safe:true,  color:'#059669' },
  { algo:'ML-DSA-65',        count:9,   safe:true,  color:'#059669' },
  { algo:'SLH-DSA',          count:5,   safe:true,  color:'#059669' },
  { algo:'ML-DSA-87',        count:3,   safe:true,  color:'#059669' },
];

const TLS_DISTRIBUTION = [
  { name:'TLS 1.0', value:8,   color:'#DC2626' },
  { name:'TLS 1.1', value:19,  color:'#EA580C' },
  { name:'TLS 1.2', value:172, color:'#F59E0B' },
  { name:'TLS 1.3', value:48,  color:'#10B981' },
];

const KEY_EXCHANGE_DIST = [
  { name:'RSA',            count:89,  safe:false },
  { name:'ECDHE-RSA',      count:94,  safe:false },
  { name:'DHE-RSA',        count:43,  safe:false },
  { name:'ECDHE',          count:27,  safe:false },
  { name:'X25519',         count:18,  safe:false },
  { name:'X25519Kyber768', count:38,  safe:true  },
  { name:'ML-KEM-768',     count:24,  safe:true  },
  { name:'ML-KEM-1024',    count:14,  safe:true  },
];
